# Docker 설정을 위한 프로파일
docker:
  # WSL2에서 Docker Desktop 사용 시 TCP로 연결
  # Windows 호스트 IP 사용 (WSL2 게이트웨이)
  host: tcp://172.20.208.1:2375
  api:
    version: 1.47
  
  # Docker 실행 제한 설정
  execution:
    timeout: 30  # 초 단위
    memory-limit: 512  # MB 단위
    cpu-shares: 512  # 0.5 CPU

# 로깅 설정
logging:
  level:
    com.github.dockerjava: DEBUG
    solid.backend.docker: DEBUG